export const readingPrompts = [
  "The gentle breeze whispered through the ancient trees, carrying stories of distant lands.",
  "Time flows like water, constant yet ever-changing, shaping everything in its path.",
  "In silence, we find the truest form of peace, where the soul can rest and breathe.",
  "Every journey begins with a single, mindful step into the unknown.",
  "Breathe deeply and let the moment embrace you with its quiet wisdom.",
  "Mountains stand tall, reminding us of strength found in stillness and patience.",
  "The morning sun paints the sky with colors that words cannot fully capture.",
  "Stars shine brightest in the darkest nights, guiding travelers home safely.",
  "Ocean waves dance endlessly, following rhythms older than human memory itself.",
  "A single candle can illuminate an entire room, just as kindness lights hearts.",
  "Rain falls softly on old rooftops, creating music that soothes the restless mind.",
  "Books hold universes within their pages, waiting for curious souls to explore them.",
  "Gardens grow slowly, teaching us the value of patience and gentle care.",
  "Birds sing at dawn, celebrating the gift of another day filled with possibilities.",
  "Tea steams gently in the cup, inviting a moment of calm reflection.",
  "Footprints in sand fade with the tide, reminding us that nothing lasts forever.",
  "Clouds drift lazily across blue skies, painting pictures that dissolve and reform constantly.",
  "The moon watches over sleeping cities, a silent guardian of dreams and hopes.",
  "Stone paths wind through forests, inviting wanderers to lose themselves in nature.",
  "Autumn leaves fall gracefully, each one a small work of art descending.",
];
